
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/whz/.cache/JetBrains/RemoteDev/dist/709c809cd569c_CLion-2024.2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-117-generic - x86_64
...
